version: '3'
services:
  proxy:
    container_name: nginx-proxy
    build: ./
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./includes:/etc/nginx/includes/
      - ./logs:/var/log/nginx
    networks:
      - reverse-proxy
    ports:
      - 8081:8081

networks:
  reverse-proxy:
    external: true